---

- hosts: all
  become: true
  pre_tasks:

  - name: update repository index (CentOS)
    tags: always
    package:
      update_cache: yes
    changed_when: false

- hosts: NFS_Servers
  become: true
  roles:
    - 
