---

- hosts: all
  become: true
  pre_tasks:

  - name: update repository index (CentOS)
    tags: always
    yum:
      update_cache: yes
    changed_when: false

  - name: installing nfs packages
    yum:
      name:
        - nfs-utils
        - rpcbind
      state: latest
  
  - name: enable and start nfs-server
    service:
      name: nfs-server
      state: started
      enabled: yes
  
  - name: enable and start rpcbind
    service:
      name: rpcbind
      state: started
      enabled: yes

  - name: disable selinux
    selinux:
      state: disabled

  - name: Creates directory
    file:
      path: /testnfs
      state: directory
      mode: 0775