- name: enable and start nfs-server
  service:
    name: nfs-server
    state: started
    enabled: yes
  when: ansible_distribution == "CentOS"

- name: enable and start rpcbind
  service:
    name: rpcbind
    state: started
    enabled: yes
  when: ansible_distribution == "CentOS"

- name: disable selinux
  selinux:
    state: disabled
  when: ansible_distribution == "CentOS"
